### ISSUE TITLE
Ajout ? - Fix embed de twitter - Pixiv

### ISSUE THREAD

**Issue by dem0nx309** [hyakanime/discord-bot#22]
Mettre un bot qui fix les embeds twitter / pixiv un peu comme saucybot , a voir si je suis motiver

**Comment by dem0nx309** [comment]
Actuellement pas en priorité , le bot SaucyBot a été mis en place pour l'instant.

**Comment by logan17111** [comment]
oh que si tu va réouvrir ça mon demonX
